/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { act, useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import lolaScene from '../../assets/Models/lola.glb'

export default function Lola(props) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF(lolaScene)
    const { actions } = useAnimations(animations, group)

    useEffect(() => {
        actions['Waving'].play()
    }, [])
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                    <group name="Lola_New_Body">
                        <skinnedMesh
                            name="Mesh"
                            geometry={nodes.Mesh.geometry}
                            material={materials.Body}
                            skeleton={nodes.Mesh.skeleton}
                        />
                        <skinnedMesh
                            name="Mesh_1"
                            geometry={nodes.Mesh_1.geometry}
                            material={materials.Face}
                            skeleton={nodes.Mesh_1.skeleton}
                        />
                        <skinnedMesh
                            name="Mesh_2"
                            geometry={nodes.Mesh_2.geometry}
                            material={materials.Hand}
                            skeleton={nodes.Mesh_2.skeleton}
                        />
                        <skinnedMesh
                            name="Mesh_3"
                            geometry={nodes.Mesh_3.geometry}
                            material={materials.Material__24}
                            skeleton={nodes.Mesh_3.skeleton}
                        />
                        <skinnedMesh
                            name="Mesh_4"
                            geometry={nodes.Mesh_4.geometry}
                            material={materials.Material__104}
                            skeleton={nodes.Mesh_4.skeleton}
                        />
                        <skinnedMesh
                            name="Mesh_5"
                            geometry={nodes.Mesh_5.geometry}
                            material={materials.Hate}
                            skeleton={nodes.Mesh_5.skeleton}
                        />
                        <skinnedMesh
                            name="Mesh_6"
                            geometry={nodes.Mesh_6.geometry}
                            material={materials.Lola}
                            skeleton={nodes.Mesh_6.skeleton}
                        />
                        <skinnedMesh
                            name="Mesh_7"
                            geometry={nodes.Mesh_7.geometry}
                            material={materials['Material #135']}
                            skeleton={nodes.Mesh_7.skeleton}
                        />
                        <skinnedMesh
                            name="Mesh_8"
                            geometry={nodes.Mesh_8.geometry}
                            material={materials['Material #147']}
                            skeleton={nodes.Mesh_8.skeleton}
                        />
                    </group>
                    <primitive object={nodes.Lola_Pelvis} />
                    <primitive object={nodes.Lola_LPlatform} />
                    <primitive object={nodes.Lola_RPlatform} />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload(lolaScene)
